base_url = "https://praxivesoftware.github.io/samurai"
title = "Samurai"
description = "Build Firefox-based browsers with ease"
default_language = "en"
compile_sass = true
build_search_index = true
minify_html = true

author = "TrickyPR"

[markdown]
highlight_code = true

[extra]
logo = "https://raw.githubusercontent.com/microsoft/fluentui-emoji/main/assets/Package/3D/package_3d.png"
release = "https://api.github.com/repos/PraxiveSoftware/samurai/releases/latest"
