base_url = "https://praxivesoftware.github.io/Samurai"
title = "Samurai"
description = "Build Firefox-based browsers with ease"
default_language = "en"
compile_sass = true
build_search_index = true
minify_html = true
theme="after-dark"

author = "TrickyPR"

[markdown]
highlight_code = true

[extra]
logo = "https://raw.githubusercontent.com/microsoft/fluentui-emoji/main/assets/Artist%20palette/3D/artist_palette_3d.png"
release = "https://api.github.com/repos/PraxiveSoftware/samurai/releases/latest"
