name: Build docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/**'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: 🔩 Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: next-9
          standalone: true
      - name: 🔩 Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - name: 🚀 Install dependencies
        run: pnpm install
      - name: Deploy docs
        run: pnpm docs:build
