name: Build docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/**'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Deploy docs
        uses: shalzz/zola-deploy-action@v0.19.1
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: docs/
          GITHUB_TOKEN: ${{ secrets.ROBOT_TOKEN }}
