name: Build docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/**'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Deploy docs
        run: docs:build
